### ISSUE TITLE
更新右侧数据显示

### ISSUE THREAD

**Issue by WuEthereum** [dforce-network/USR#15]
usr需要更新一些信息，这是原型，稍后设计稿会更新。https://axhub.im/pro/a580bc7640a5b20a
1.You can withdraw 0 USDx 改成 You have 123.45 USDx saving in USR.
2.右侧USR balance去掉
3.新增：Total USDx in USR: 1111.889 USDx
获取USR合约里USDx的余额（balance of）就可以
4.新增：Liquidity Remaining: 13333.12 USDx
接口：share接口
5.1 USR = 1.00183430 USDx修改为：USR Net Worth: 1.00183430 USDx
6.USDx Annual Rate修改为：USDx Saving Rate
7.Saving Origination Fee: 0.1%
接口：originationFee(unit256)
18位精度

中文：https://axhub.im/pro/a580bc7640a5b20a/#g=1&p=deposit_redeem-cn
您有123.55USDx正在生息
存入USDx的总量
剩余可存入USDx数量
USR净值
USR年化利率
存款手续费率

**Comment by merlin-li** [comment]
已处理
