### ISSUE TITLE
Menu的文字更新

### ISSUE THREAD

**Issue by WuEthereum** [dforce-network/USR#16]
1.单词首字母大写：
（1）Saving and Accuring interest修改为：Saving and Accuring Interest
（2）Collateral Lending Dashboard
2.Menu位置的描述dForce instant…,去掉dForce。有的显示器描述会显示三行，所以这里去掉
![image](https://user-images.githubusercontent.com/32732224/79428522-d75c7880-7ff8-11ea-88d5-cc72b3d3585b.png)
![image](https://user-images.githubusercontent.com/32732224/79429676-6ddd6980-7ffa-11ea-81ad-524b47125e75.png)

**Comment by merlin-li** [comment]
已处理
