### ISSUE TITLE
接口返回数据

### ISSUE THREAD

**Issue by WuEthereum** [dforce-network/USR#2]
1.You can withdraw 98,991,000.00 USDx
getTotalBalance直接拿到做精度处理就可以
2.输入框输入USR数量，可以得到多少USDx，需要和合约内的USDx余额做比较，校验前后
（1）如果输入USR数量>MAX。提示余额不足
（2）You will receive at least 0 USDx > 合约内USDx Balance of。提示流动性不足
其中2.(2)，我让设计添加以下设计稿
3.合约内还可以存入多少USDx数量，需要设计一下提示信息

**Comment by merlin-li** [comment]
fixed
