### ISSUE TITLE
deposit/redeem返回结果后，数据需要刷新

### ISSUE THREAD

**Issue by WuEthereum** [dforce-network/USR#5]
deposit/redeem执行过程中：
1.需要出现history的记录和正在执行动作；
2.History需要按照时间倒序排列，就是最近的一条记录在最上面
3.history数据超过4条后，采用右侧滑动的方式查看history：类似于这个：https://test.xswap.me/
![image](https://user-images.githubusercontent.com/32732224/78977583-ed76be80-7b4a-11ea-8986-75a5dbd47dd6.png)
4.返回结果后，数据需要刷新(余额等其他相关数据)，数据框数据需要清空
![image](https://user-images.githubusercontent.com/32732224/78976882-b653dd80-7b49-11ea-9445-c68464704755.png)

**Comment by merlin-li** [comment]
fixed
